ALTER TYPE "EventType" ADD VALUE 'IMPACT_OBSERVED';
ALTER TABLE "LiveLesson"
ADD COLUMN "impactStartedAt" TIMESTAMP(3),
ADD COLUMN "impactRunningSince" TIMESTAMP(3),
ADD COLUMN "impactElapsedMs" INTEGER NOT NULL DEFAULT 0;
