import { describe, expect, it } from "vitest";
import { activityElapsed, assignGroups, groupRepresentatives, mapComplete, mapPhase, timingStats, type MapCard, type MapSignal } from "@/lib/classroom-completion";
import { escapeHtml, TELEMETRY_FIELDS } from "@/lib/classroom-archive";
describe("classroom completion boundaries", () => {
  it("gives 25 people five balanced groups and handles small/uneven classes", () => {
    for (const size of [0, 1, 6, 24, 25, 26]) { const groups = Object.values(assignGroups(Array.from({ length: size }, (_, i) => String(i)))); expect(groups).toHaveLength(size); for (const group of new Set(groups)) expect(groups.filter(value => value === group).length).toBeLessThanOrEqual(5); }
    expect(new Set(Object.values(assignGroups(Array.from({ length: 25 }, (_, i) => String(i))))).size).toBe(5);
  });
  it("keeps exact 3/7/2 minute boundaries and pauses independent clocks", () => { expect([179999, 180000, 599999, 600000, 720000].map(mapPhase)).toEqual([0, 1, 1, 2, 2]); expect(activityElapsed({ startedAt: 1, runningSince: null, elapsedMs: 4500, closedAt: null }, 999999, 10000)).toBe(4500); expect(activityElapsed({ startedAt: 1, runningSince: 100, elapsedMs: 4500, closedAt: null }, 99999, 10000)).toBe(10000); });
  it("requires text in every layer", () => { const signals = ["macro", "micro", "self"].map(layer => ({ id: layer, layer, text: "信号", priority: "now" })) as MapSignal[]; expect(mapComplete(signals)).toBe(true); expect(mapComplete(signals.slice(0, 2))).toBe(false); expect(mapComplete([{ ...signals[0], text: " " }, ...signals.slice(1)])).toBe(false); });
  it("excludes unsubmitted candidates and resolves nomination ties consistently", () => { const base = { name: "同学", group: 1, signals: [], version: 1, submitted: true, nominations: 2 }; const cards: MapCard[] = [{ ...base, studentId: "b" }, { ...base, studentId: "a" }, { ...base, studentId: "c", nominations: 9, submitted: false }]; expect(groupRepresentatives(cards)[0].studentId).toBe("a"); expect(groupRepresentatives(cards.toReversed())[0].studentId).toBe("a"); });
  it("uses valid votes as denominator and distinguishes abstentions and not entered", () => { const stats = timingStats([{ entered: true, choice: "A", reason: "submitted", elapsedMs: 5 }, { entered: true, choice: "B", reason: "submitted", elapsedMs: 6 }, { entered: true, choice: null, reason: "timeout", elapsedMs: 10000 }, { entered: false, choice: null, reason: null, elapsedMs: null }]); expect(stats).toMatchObject({ total: 3, voted: 2, noAnswer: 1, pending: 0, majorityImmediate: false }); expect(stats.options[0].percent).toBe(50); expect(timingStats([]).options.every(option => option.percent === 0)).toBe(true); });
  it("documents all nineteen observations and escapes exported student text", () => { expect(TELEMETRY_FIELDS).toHaveLength(19); expect(new Set(TELEMETRY_FIELDS.map(field => field[0])).size).toBe(19); expect(escapeHtml('<img src=x onerror="alert(1)">&')).toBe('&lt;img src=x onerror=&quot;alert(1)&quot;&gt;&amp;'); });
});
