import { expect, test } from "@playwright/test";
import { Pool } from "pg";
import { mkdir } from "node:fs/promises";
import { join } from "node:path";
import { tmpdir } from "node:os";
test.use({ channel: process.env.PLAYWRIGHT_CHANNEL });
test("role decisions synchronize, preserve privacy, and settle unanswered deadlines", async ({ browser, baseURL }) => {
  test.setTimeout(180000);
  const output = process.env.CLASSROOM_QA_OUTPUT || join(tmpdir(), "classroom-decision"); await mkdir(output, { recursive: true });
  const contexts = await Promise.all(Array.from({ length: 6 }, () => browser.newContext({ baseURL, viewport: { width: 1440, height: 1080 } })));
  const [teacher, first, second, third, late, stranger] = contexts;
  const pool = new Pool({ connectionString: process.env.DATABASE_URL });
  let classId = "", id = "";
  try {
    const login = async (context: typeof teacher, username: string, portal = "student") => expect((await context.request.post("/api/auth/login", { data: { username, portal, password: "SmartAgri2026!" } })).status()).toBe(200);
    await login(teacher, "teacher-demo", "teacher"); const stamp = Date.now();
    const create = await teacher.request.post("/api/teacher/classes", { data: { name: `角色决策演练 ${stamp.toString().slice(-5)}`, academicYear: "2026-2027", semester: "第一学期" } }); expect(create.status()).toBe(201); classId = (await create.json()).id;
    for (let i = 0; i < 4; i++) expect((await teacher.request.post(`/api/teacher/classes/${classId}/members`, { data: { displayName: ["陈同学", "葛同学", "林同学", "赵同学"][i], username: `decision_${stamp}_${i}`, studentNo: `D${stamp}${i}` } })).status()).toBe(201);
    await Promise.all([first, second, third, late].map((context, index) => login(context, `decision_${stamp}_${index}`))); await login(stranger, "student-demo");
    id = (await (await teacher.request.post("/api/classroom", { data: { classId, rehearsal: true } })).json()).id;
    const api = () => `/api/classroom/${id}`;
    const snapshot = async () => (await teacher.request.get(`${api()}?view=teacher`)).json();
    const own = async (context = first) => (await context.request.get(`${api()}?view=student`)).json();
    const command = async (action: string, extra = {}) => { const state = await snapshot(); expect((await teacher.request.patch(api(), { data: { action, version: state.version, ...extra } })).status()).toBe(200); };
    const submit = (context: typeof first, choice: string, extra = {}) => context.request.post(`${api()}/decision`, { data: { choice, ...extra } });
    for (const context of [first, second]) expect((await context.request.post(api(), { data: { action: "join" } })).status()).toBe(200);
    expect((await submit(first, "C")).status()).toBe(409);
    await command("start"); await command("impact-start");
    await pool.query('UPDATE "LiveLesson" SET "impactRunningSince"=NOW()-INTERVAL \'40 seconds\' WHERE "id"=$1', [id]);
    expect((await first.request.post(`${api()}/impact`, { data: { batchId: crypto.randomUUID(), observations: ["news", "farmer", "team", "news"].map((region, index) => ({ kind: "view", region, atMs: 27000 + index * 2500, durationMs: 0 })) } })).status()).toBe(200);
    await command("stage", { stage: 2 });
    expect((await first.request.post(`${api()}/impact`, { data: { batchId: crypto.randomUUID(), observations: [], complete: true } })).status()).toBe(200);
    for (const path of ["transform", "stay", "upgrade"]) expect((await first.request.post(`${api()}/paths`, { data: { path } })).status()).toBe(200);
    const [t, s, m, screen] = await Promise.all([teacher.newPage(), first.newPage(), second.newPage(), teacher.newPage()]);
    const errors: string[] = []; for (const page of [t, s, m, screen]) page.on("pageerror", error => errors.push(error.message));
    await screen.setViewportSize({ width: 1920, height: 1080 }); await m.setViewportSize({ width: 390, height: 844 });
    await Promise.all([t.goto(`/teacher/classroom/${id}`), s.goto(`/student/classroom/${id}`), m.goto(`/student/classroom/${id}`), screen.goto(`/classroom/${id}/screen`)]);
    await t.getByRole("button", { name: "发起3分钟决策", exact: true }).click(); await t.getByRole("dialog").getByRole("button", { name: "确认", exact: true }).click();
    await expect(s.getByRole("button", { name: "C 人机协同方案" })).toBeEnabled();
    expect((await submit(second, "B")).status()).toBe(409);
    expect((await submit(stranger, "A")).status()).toBe(403);
    expect((await submit(teacher, "A")).status()).toBe(403);
    expect((await submit(first, "Z")).status()).toBe(400);
    expect((await submit(first, "C", { studentId: "someone-else" })).status()).toBe(400);
    expect((await submit(first, "C", { trace: [{ choice: "C", atMs: 179999 }] })).status()).toBe(400);
    await s.getByRole("button", { name: "开启情境声音" }).click();
    await expect.poll(() => s.locator(".decision-farmer audio").evaluate((element: HTMLAudioElement) => element.duration)).toBeGreaterThan(5);
    await expect.poll(() => s.locator(".decision-farmer audio").evaluate((element: HTMLAudioElement) => element.currentTime)).toBeGreaterThan(0);
    await s.getByRole("button", { name: "B 坚持纯真人" }).click();
    await s.getByRole("button", { name: "C 人机协同方案" }).click();
    await command("pause"); await expect(s.getByRole("button", { name: "确认我的选择" })).toBeDisabled();
    await expect.poll(() => s.locator(".decision-farmer audio").evaluate((element: HTMLAudioElement) => element.paused)).toBe(true);
    const frozen = (await snapshot()).decision.elapsedMs; await s.waitForTimeout(1100); expect((await snapshot()).decision.elapsedMs).toBe(frozen);
    expect((await submit(first, "C")).status()).toBe(409);
    await s.reload(); await expect(s.getByRole("button", { name: "C 人机协同方案" })).toHaveAttribute("aria-pressed", "true");
    await command("reset", { minutes: 6 }); expect((await snapshot()).decision.elapsedMs).toBe(frozen);
    await command("resume");
    // Late arrival during an open decision joins the same deadline and cohort.
    expect((await third.request.post(api(), { data: { action: "join" } })).status()).toBe(200);
    for (const context of [second, third]) for (const path of ["transform", "stay", "upgrade"]) expect((await context.request.post(`${api()}/paths`, { data: { path } })).status()).toBe(200);
    await s.getByRole("button", { name: "确认我的选择" }).click(); await s.getByRole("dialog").getByRole("button", { name: "确认提交", exact: true }).click();
    await expect(s.getByRole("heading", { name: "已提交 C · 人机协同方案" })).toBeVisible();
    const retries = await Promise.all([submit(first, "C"), submit(first, "C")]); expect(retries.map(response => response.status())).toEqual([200, 200]); expect((await submit(first, "A")).status()).toBe(409);
    expect((await submit(third, "D")).status()).toBe(200);
    await s.getByRole("button", { name: "查看我的个人报告" }).click(); await expect(s.getByText("协同融合型", { exact: true })).toBeVisible();
    await expect(s.getByText("4 条记录 · 仅标记实际操作时点")).toBeVisible();
    expect((await teacher.request.get(`${api()}/decision`)).status()).toBe(403);
    expect((await stranger.request.get(`${api()}/decision`)).status()).toBe(403);
    expect((await own()).decisionStats).toBeUndefined();
    const publicData = await (await teacher.request.get(`${api()}?view=screen`)).json(); expect(publicData.ownDecision).toBeUndefined(); expect(publicData.roster).toBeUndefined();
    await expect(screen.getByTestId("decision-submitted")).toHaveText("2 / 3"); await expect(screen.getByTestId("decision-cd")).toHaveText("100%");
    await m.getByRole("button", { name: "A 全面转向 AI" }).click();
    expect(await m.evaluate(() => document.documentElement.scrollWidth > innerWidth)).toBe(false);
    await m.screenshot({ path: join(output, "第四步-学生决策手机.png"), fullPage: true });
    await s.screenshot({ path: join(output, "第四步-个人决策报告.png"), fullPage: true });
    await second.setOffline(true);
    // Advance only the disposable fixture to test the exact deadline without a 3-minute wait.
    await pool.query('UPDATE "LiveLesson" SET "decisionRunningSince"=NOW()-INTERVAL \'160 seconds\', "decisionElapsedMs"=0 WHERE "id"=$1', [id]);
    await expect(screen.locator(".decision-countdown")).toHaveClass(/urgent/);
    await pool.query('UPDATE "LiveLesson" SET "decisionRunningSince"=NOW()-INTERVAL \'181 seconds\' WHERE "id"=$1', [id]);
    await expect(screen.getByTestId("decision-unanswered")).toHaveText("1");
    await second.setOffline(false); await m.reload(); await expect(m.getByRole("heading", { name: "本次决策：未作答" })).toBeVisible();
    expect((await own(second)).ownDecision).toMatchObject({ choice: null, reason: "timeout", elapsedMs: 180000 });
    const emptyReport = await (await second.request.get(`${api()}/decision`)).json(); expect(emptyReport.trace).toEqual([]); expect(emptyReport.impact).toEqual([]);
    expect((await submit(second, "A")).status()).toBe(409);
    expect((await submit(first, "C")).status()).toBe(200);
    await late.request.post(api(), { data: { action: "join" } }); expect((await own(late)).ownDecision.entered).toBe(false);
    expect((await snapshot()).decisionStats).toMatchObject({ total: 3, submitted: 2, pending: 0, noAnswer: 1, cdPercent: 100, cdCohortPercent: 66.7 });
    const records = await pool.query('SELECT "payload" FROM "LearningEvent" WHERE "liveLessonId"=$1 AND "eventType"=\'DECISION_RECORDED\'', [id]); expect(records.rows).toHaveLength(3); expect(records.rows.filter(row => row.payload.reason === "timeout")[0].payload.choice).toBeNull();
    await screen.screenshot({ path: join(output, "第四步-班级决策大屏.png"), fullPage: true });
    expect(await screen.locator(".decision-discussion").evaluate(element => element.getBoundingClientRect().bottom <= innerHeight)).toBe(true);
    await command("stage", { stage: 3 }); await s.reload(); await expect(s.getByRole("button", { name: "查看我的个人报告" })).toBeVisible();
    await command("end"); expect((await first.request.get(`${api()}/decision`)).status()).toBe(200);
    // Early teacher closure also finalizes unsubmitted students and cannot reopen the decision.
    id = (await (await teacher.request.post("/api/classroom", { data: { classId, rehearsal: true } })).json()).id;
    await first.request.post(api(), { data: { action: "join" } }); await command("start"); await command("stage", { stage: 2 }); await command("decision-start"); await command("stage", { stage: 3 });
    expect((await own()).ownDecision).toMatchObject({ choice: null, reason: "teacher" });
    await command("stage", { stage: 2 }); expect((await teacher.request.patch(api(), { data: { action: "decision-start", version: (await snapshot()).version } })).status()).toBe(409);
    await command("end");
    // With no subscribed clients, the first expired submission must commit closure before returning 409.
    id = (await (await teacher.request.post("/api/classroom", { data: { classId, rehearsal: false } })).json()).id;
    await first.request.post(api(), { data: { action: "join" } }); await command("start"); await command("stage", { stage: 2 }); await command("decision-start");
    await pool.query('UPDATE "LiveLesson" SET "decisionRunningSince"=NOW()-INTERVAL \'181 seconds\' WHERE "id"=$1', [id]);
    expect((await submit(first, "D")).status()).toBe(409);
    const finalized = await pool.query('SELECT "decisionReason", "decisionChoice" FROM "LessonPresence" WHERE "lessonId"=$1', [id]); expect(finalized.rows[0]).toEqual({ decisionReason: "timeout", decisionChoice: null });
    const formal = await pool.query('SELECT "source", "payload" FROM "LearningEvent" WHERE "liveLessonId"=$1 AND "eventType"=\'DECISION_RECORDED\'', [id]); expect(formal.rows[0].source).toBe("classroom"); expect(formal.rows[0].payload.rehearsal).toBe(false);
    expect(errors).toEqual([]);
  } finally {
    if (id) { const state = await (await teacher.request.get(`/api/classroom/${id}?view=teacher`)).json(); if (state.version && state.status !== "ENDED") await teacher.request.patch(`/api/classroom/${id}`, { data: { action: "end", version: state.version } }); }
    if (classId) await teacher.request.patch(`/api/teacher/classes/${classId}`, { data: { isArchived: true } });
    await Promise.all(contexts.map(context => context.close())); await pool.end();
  }
});
