import { expect, test } from "@playwright/test";
import { mkdir } from "node:fs/promises";
import { join } from "node:path";
import { tmpdir } from "node:os";

test.use({ channel: process.env.PLAYWRIGHT_CHANNEL, viewport: { width: 1440, height: 1000 } });
test("teacher, two students and display share a persistent, authorized classroom", async ({ browser, baseURL }) => {
  test.setTimeout(180000);
  const output = process.env.CLASSROOM_QA_OUTPUT ?? join(tmpdir(), "smart-classroom-qa");
  await mkdir(output, { recursive: true });
  const contexts = await Promise.all(Array.from({ length: 4 }, () => browser.newContext({ baseURL, viewport: { width: 1440, height: 1000 } })));
  const [teacher, first, second, outsider] = contexts;
  const pages = await Promise.all([teacher, first, second].map(context => context.newPage()));
  const [t, s1, s2] = pages;
  const errors: string[] = [];
  pages.forEach(page => page.on("pageerror", error => errors.push(error.message)));
  async function login(context: typeof teacher, username: string, portal = "student") {
    const response = await context.request.post("/api/auth/login", { data: { username, password: "SmartAgri2026!", portal } });
    expect(response.ok()).toBeTruthy();
  }
  try {
    await login(teacher, "teacher-demo", "teacher");
    const stamp = Date.now().toString();
    const className = `课堂联调 ${stamp.slice(-6)}`;
    const created = await teacher.request.post("/api/teacher/classes", { data: { name: className, academicYear: "2026-2027", semester: "第一学期" } });
    expect(created.status()).toBe(201);
    const classroom = await created.json();
    for (const [index, name] of ["陈同学", "葛同学"].entries()) {
      const response = await teacher.request.post(`/api/teacher/classes/${classroom.id}/members`, { data: { displayName: name, username: `cq_${stamp}_${index}`, studentNo: `CQ${stamp}${index}` } });
      expect(response.status()).toBe(201);
    }
    await Promise.all([login(first, `cq_${stamp}_0`), login(second, `cq_${stamp}_1`), login(outsider, "student-demo")]);
    await t.goto("/teacher/classroom");
    await t.getByLabel("授课班级").selectOption(classroom.id);
    await t.getByRole("button", { name: "创建课堂" }).click();
    await expect(t).toHaveURL(/\/teacher\/classroom\/[^/]+$/);
    const id = t.url().split("/").pop()!;
    const api = `/api/classroom/${id}`;
    await expect(t.getByRole("button", { name: "开始课堂", exact: true })).toBeEnabled();
    const duplicate = await teacher.request.post("/api/classroom", { data: { classId: classroom.id, rehearsal: true } });
    expect(duplicate.status()).toBe(409);
    expect((await outsider.request.get(`${api}?view=student`)).status()).toBe(403);
    expect((await first.request.get(`${api}?view=teacher`)).status()).toBe(403);
    expect((await first.request.patch(api, { data: { action: "start", version: 1 } })).status()).toBe(403);
    await Promise.all([s1.goto(`/student/classroom/${id}`), s2.goto(`/student/classroom/${id}`)]);
    await s1.getByRole("button", { name: "加入本次课堂" }).click();
    await s2.getByRole("button", { name: "加入本次课堂" }).click();
    await s1.getByRole("button", { name: "我准备好了" }).click();
    await expect(t.getByTestId("joined-count")).toHaveText("2/2");
    await expect(t.getByTestId("ready-count")).toHaveText("1");
    const screen = await teacher.newPage();
    screen.on("pageerror", error => errors.push(error.message));
    await screen.setViewportSize({ width: 1920, height: 1080 });
    await screen.goto(`/classroom/${id}/screen`);
    const screenData = await (await teacher.request.get(`${api}?view=screen`)).json();
    const studentData = await (await first.request.get(`${api}?view=student`)).json();
    expect(screenData.roster).toBeUndefined(); expect(studentData.roster).toBeUndefined();
    await expect(screen.locator(".teacher-sidebar")).toHaveCount(0);
    await expect(screen.getByText("陈同学", { exact: true })).toHaveCount(0);
    await expect(s1.locator(".classroom-stage-track button").nth(1)).toBeDisabled();
    await t.screenshot({ path: join(output, "课堂-教师候场.png"), fullPage: true });
    await s1.screenshot({ path: join(output, "课堂-学生候场.png") });
    await screen.screenshot({ path: join(output, "课堂-大屏候场.png") });
    await t.getByRole("button", { name: "开始课堂", exact: true }).click();
    await expect(s1.locator(".classroom-status")).toHaveText("课堂进行中");
    await expect(s2.locator(".classroom-status")).toHaveText("课堂进行中");
    await expect(screen.locator(".classroom-status")).toHaveText("课堂进行中");
    await t.getByRole("button", { name: "暂停课堂" }).click();
    await expect(s1.locator(".classroom-status")).toHaveText("课堂已暂停");
    const frozen = await s1.getByTestId("lesson-clock").innerText();
    await s1.waitForTimeout(1200);
    expect(await s1.getByTestId("lesson-clock").innerText()).toBe(frozen);
    await s1.reload();
    await expect(s1.locator(".classroom-status")).toHaveText("课堂已暂停");
    await expect(s1.getByRole("button", { name: "已准备好，等待老师安排" })).toBeVisible();
    await t.getByRole("button", { name: "下一阶段", exact: true }).click();
    await t.getByRole("dialog").getByRole("button", { name: "确认", exact: true }).click();
    await expect(s1.getByTestId("current-stage")).toHaveText("路径参考");
    await expect(screen.getByTestId("current-stage")).toHaveText("路径参考");
    await expect(s1.getByTestId("lesson-clock")).toHaveText("02:00");
    await expect(t.getByLabel("设置当前阶段时长")).toHaveValue("2");
    await t.getByLabel("设置当前阶段时长").fill("3");
    await t.getByRole("button", { name: "重置计时" }).click();
    await t.getByRole("dialog").getByRole("button", { name: "确认", exact: true }).click();
    await expect(s1.getByTestId("lesson-clock")).toHaveText("03:00");
    await expect(t.getByTestId("joined-count")).toHaveText("2/2");
    await t.getByRole("button", { name: "继续课堂" }).click();
    await expect(s2.locator(".classroom-status")).toHaveText("课堂进行中");
    await second.setOffline(true);
    await expect(s2.getByRole("status")).toHaveText("重新连接中");
    await t.getByRole("button", { name: "下一阶段", exact: true }).click();
    await t.getByRole("dialog").getByRole("button", { name: "确认", exact: true }).click();
    await expect(s1.getByTestId("current-stage")).toHaveText("角色决策");
    await expect.poll(async () => (await (await teacher.request.get(`${api}?view=teacher`)).json()).online, { timeout: 30000 }).toBe(1);
    await second.setOffline(false);
    await expect(s2.getByTestId("current-stage")).toHaveText("角色决策", { timeout: 15000 });
    await expect.poll(async () => (await (await teacher.request.get(`${api}?view=teacher`)).json()).online, { timeout: 15000 }).toBe(2);
    await s2.reload(); await expect(s2.getByTestId("current-stage")).toHaveText("角色决策");
    const latest = await (await teacher.request.get(`${api}?view=teacher`)).json();
    const concurrent = await Promise.all([0, 1].map(() => teacher.request.patch(api, { data: { action: "stage", stage: 3, version: latest.version } })));
    expect(concurrent.map(response => response.status()).sort()).toEqual([200, 409]);
    await expect(s1.getByTestId("current-stage")).toHaveText("三层变化识别");
    await expect(t.getByTestId("current-stage")).toHaveText("三层变化识别");
    for (const title of ["变化地图协作", "调整时机投票"]) {
      await t.getByRole("button", { name: "下一阶段", exact: true }).click();
      await t.getByRole("dialog").getByRole("button", { name: "确认", exact: true }).click();
      await expect(s1.getByTestId("current-stage")).toHaveText(title);
      await expect(screen.getByTestId("current-stage")).toHaveText(title);
      await expect(t.getByTestId("current-stage")).toHaveText(title);
    }
    await t.screenshot({ path: join(output, "课堂-教师控场.png"), fullPage: true });
    await screen.screenshot({ path: join(output, "课堂-大屏同步.png") });
    await s1.setViewportSize({ width: 390, height: 844 });
    await s1.screenshot({ path: join(output, "课堂-学生手机.png"), fullPage: true });
    expect(await s1.evaluate(() => document.documentElement.scrollWidth > innerWidth)).toBe(false);
    await t.getByRole("button", { name: "结束课堂", exact: true }).click();
    await t.getByRole("dialog").getByRole("button", { name: "确认", exact: true }).click();
    await expect(s1.locator(".classroom-status")).toHaveText("课堂已结束");
    const ended = await (await teacher.request.get(`${api}?view=teacher`)).json();
    expect((await teacher.request.patch(api, { data: { action: "start", version: ended.version } })).status()).toBe(409);
    expect((await first.request.post(api, { data: { action: "join" } })).status()).toBe(409);
    await s1.reload(); await expect(s1.locator(".classroom-status")).toHaveText("课堂已结束");
    expect(errors).toEqual([]);
  } finally { await Promise.all(contexts.map(context => context.close())); }
});
