ALTER TYPE "EventType" ADD VALUE 'CHANGE_MAP_SAVED';
ALTER TYPE "EventType" ADD VALUE 'CHANGE_MAP_SHARED';
ALTER TYPE "EventType" ADD VALUE 'GROUP_MAP_VIEWED';
ALTER TYPE "EventType" ADD VALUE 'MAP_NOMINATED';
ALTER TYPE "EventType" ADD VALUE 'TIMING_VOTED';
ALTER TABLE "LiveLesson"
 ADD COLUMN "frameworkRunningSince" TIMESTAMP(3), ADD COLUMN "frameworkElapsedMs" INTEGER NOT NULL DEFAULT 0,
 ADD COLUMN "mapStartedAt" TIMESTAMP(3), ADD COLUMN "mapRunningSince" TIMESTAMP(3), ADD COLUMN "mapElapsedMs" INTEGER NOT NULL DEFAULT 0,
 ADD COLUMN "mapClosedAt" TIMESTAMP(3), ADD COLUMN "mapGroups" JSONB NOT NULL DEFAULT '{}', ADD COLUMN "mapPresentation" JSONB,
 ADD COLUMN "voteStartedAt" TIMESTAMP(3), ADD COLUMN "voteRunningSince" TIMESTAMP(3), ADD COLUMN "voteElapsedMs" INTEGER NOT NULL DEFAULT 0,
 ADD COLUMN "voteClosedAt" TIMESTAMP(3), ADD COLUMN "signalsVisible" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "LessonPresence"
 ADD COLUMN "frameworkFirstMs" INTEGER, ADD COLUMN "frameworkCompletedMs" INTEGER,
 ADD COLUMN "mapSignals" JSONB NOT NULL DEFAULT '[]', ADD COLUMN "mapVersion" INTEGER NOT NULL DEFAULT 0,
 ADD COLUMN "mapSubmittedAt" TIMESTAMP(3), ADD COLUMN "mapIndependentMs" INTEGER, ADD COLUMN "mapEntryMs" INTEGER, ADD COLUMN "mapNominatedId" TEXT,
 ADD COLUMN "groupInteractions" INTEGER NOT NULL DEFAULT 0,
 ADD COLUMN "voteEnteredAt" TIMESTAMP(3), ADD COLUMN "voteChoice" TEXT, ADD COLUMN "voteSubmittedAt" TIMESTAMP(3),
 ADD COLUMN "voteResponseMs" INTEGER, ADD COLUMN "voteReason" TEXT;
