ALTER TYPE "EventType" ADD VALUE 'PATH_REFERENCE_READ';
ALTER TABLE "LiveLesson" ADD COLUMN "impactClosedAt" TIMESTAMP(3), ADD COLUMN "impactResultsVisible" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "LessonPresence" ADD COLUMN "impactEntryMs" INTEGER NOT NULL DEFAULT 0, ADD COLUMN "impactSyncedAt" TIMESTAMP(3), ADD COLUMN "pathsViewed" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[];
